config/routes.rb
Rails.application.routes.draw do
  root to: 'titles#index', root: ''
  resources :titles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/title.rb
class Title < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :release_year, presence: true
  validates :rating, presence: true
  validates :media_type, presence: true

  scope :filter_by_name, -> (name) { where('name like ?', "%#{name}%")}
  scope :filter_by_director, -> (director) { where('director like ?', "%#{director}%")}
  scope :filter_by_cast, -> (cast) { where('cast like ?', "%#{cast}%")}
  scope :filter_by_rating, -> (rating) { where('rating like ?', "%#{rating}%")}
  scope :filter_by_year, -> (year) { where('year like ?', "%#{year}%")}
  scope :filter_by_duration, -> (duration) { where('duration like ?', "%#{duration}%")}
  scope :filter_by_country, -> (country) { where('country like ?', "%#{country}%")}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  def index
    @titles = Title.all.order(:name => :asc)
    title_params.each do |key, value|
      @titles = @titles.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  def show
  end

  def new
    @title = Title.new
  end

  def edit
  end

  def create
    @title = Title.new(title_params)
    if @title.save
      flash[:notice] = "Title was created successfully"
      redirect_to title_path(@title)
    else
      render "new"
    end
  end

  def update
    if @title.update(title_params)
      flash[:notice] = "Title was updated successfully"
      redirect_to @title
    else
      render "edit"
    end
  end

  def destroy
    @title.destroy
    redirect_to titles_path
  end

  private

  def set_title
    @title = Title.find_by(id: params[:id])
  end

  def title_params
    params.permit(:name, :description, :director, :cast, :country, :release_year, :rating, :duration, :media_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
      - msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Netflix App
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light.container-fluid
      %a.navbar-brand{:href => "#"} Netflix Titles
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      %div.navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
          %li.nav-item
            %a.nav-link{:href => "#"} Link
          %li.nav-item.dropdown
            %a.navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Dropdown
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                %a.dropdown-item{:href => "#"} Action
              %li
                %a.dropdown-item{:href => "#"} Another action
              %li
                %hr.dropdown-divider/
              %li
                %a.dropdown-item{:href => "#"} Something else here
          %li.nav-item
            %a.nav-link.disabled Disabled
    = render 'layouts/messages'
    = yield

app/views/titles/_form.html.haml
- if @title.errors.any?
  %h2 The following errors prevented the title from being saved. 
  - @title.errors.full_messages.each do |msg|
    %li= msg
= form_with(model: @title, local: true)  do |f|
  %p 
    = f.label :title
    %br
    = f.text_field :name
  %p 
    = f.label :description
    %br
    = f.text_area :description
  %p 
    = f.label :rating
    %br
    = f.text_field :rating
  %p 
    = f.label :director
    %br
    = f.text_field :director
  %p 
    = f.label :cast
    %br
    = f.text_area :cast
  %p 
    = f.label :year
    %br
    = f.text_field :release_year
  %p 
    = f.label :country
    %br
    = f.text_field :country
  %p 
    = f.label :length
    %br
    = f.text_field :duration
  %p 
    = f.label :media_type
    %br
    = f.text_field :media_type
  %p 
    = f.submit

app/views/titles/edit.html.haml
%h2 Edit Title 
= render 'form'
= link_to 'Home', titles_path
   

app/views/titles/index.html.haml
%h1 Movie List
= form_tag "/titles", method: "GET" do
  = label_tag :title
  = text_field_tag :name, params[:name]
  = submit_tag "Search"

- @titles.each do |title|
  %h2= link_to title.name, title_path(title) #{title.name}
  %h4.colspan-3 Actions:
  = link_to 'Edit', edit_title_path(title)
  = link_to 'Delete', title_path(title), method: :delete, data: { confirm: "Are you sure?"}
  %hr

app/views/titles/new.html.haml
%h2 Create a new Title 
= render 'form'
= link_to 'Home', titles_path
  

app/views/titles/show.html.haml
%h2 
  Title: 
  = @title.name
%h3 
  Description: 
  = @title.description
%h4 
  Director: 
  = @title.director
%h4 
  Cast: 
  = @title.cast
%h4 
  Rating: 
  = @title.rating
%h4 
  Year: 
  = @title.release_year
%h4 
  Duration: 
  = @title.duration
%h4 
  Country: 
  = @title.country
= link_to 'Edit', edit_title_path(@title)
= link_to 'Home', titles_path


  